// Generated by scripts/host-args.ts from the server's tool schemas (npm run build). Do not edit.
// The arguments each host command receives: C.<tool> = function (a: Args["<tool>"]) { ... }.

interface Args {
  add_layer: {
    comp_id: number;
    kind: "solid" | "text" | "shape" | "null" | "adjustment" | "footage" | "precomp" | "camera" | "light";
    options?: {
      name?: string;
      color?: number[];
      size?: number[];
      duration?: number;
      text?: string;
      item_id?: number;
      center?: number[];
      light_type?: "point" | "spot" | "parallel" | "ambient";
      start?: number;
      in?: number;
      out?: number;
      position?: number[];
      three_d?: boolean;
      box_size?: number[];
      text_style?: { [key: string]: unknown };
      anchor?: "center" | "top_left" | "top" | "top_right" | "left" | "right" | "bottom_left" | "bottom" | "bottom_right";
      shape?: {
        type?: "rect" | "ellipse" | "star" | "polygon" | "path";
        points?: number;
        outer_radius?: number;
        inner_radius?: number;
        vertices?: number[][];
        in_tangents?: number[][];
        out_tangents?: number[][];
        closed?: boolean;
        size?: number[];
        fill?: number[];
        stroke?: number[];
        stroke_width?: number;
        roundness?: number;
        fill_opacity?: number;
        stroke_opacity?: number;
        dashes?: number[];
        line_cap?: "butt" | "round" | "square";
        line_join?: "miter" | "round" | "bevel";
        name?: string;
        position?: number[];
        rotation?: number;
        opacity?: number;
      };
      fit_to?: {
        layer_id: number;
        padding?: number | number[];
      };
    };
  };
  add_layer_style: {
    layer_id: number;
    style: "drop_shadow" | "inner_shadow" | "outer_glow" | "inner_glow" | "bevel_emboss" | "satin" | "color_overlay" | "gradient_overlay" | "stroke";
    params?: { [key: string]: number | string | boolean | number[] };
    enabled?: boolean;
  };
  add_marker: {
    layer_id?: number;
    comp_id?: number;
    time: number;
    comment?: string;
    duration?: number;
    chapter?: string;
    url?: string;
    label?: number;
  };
  add_mask: {
    layer_id: number;
    shape: {
      type: "rect" | "ellipse" | "polygon" | "path";
      position?: number[];
      size?: number[];
      points?: number[][];
      vertices?: number[][];
      in_tangents?: number[][];
      out_tangents?: number[][];
      closed?: boolean;
    };
    mode?: "add" | "subtract" | "intersect" | "lighten" | "darken" | "difference" | "none";
    inverted?: boolean;
    feather?: number;
    feather_xy?: number[];
    opacity?: number;
    expansion?: number;
    name?: string;
  };
  add_property: {
    layer_id: number;
    match_name: string;
    group_path?: string | (string | number)[];
  };
  add_sfx: {
    comp_id: number;
    path: string;
    time: number;
    align?: "peak" | "start";
    volume?: number;
    fade_in?: number;
    fade_out?: number;
    max_duration?: number;
    lead_in?: number;
    name?: string;
  };
  add_shape: {
    layer_id: number;
    shape: {
      type?: "rect" | "ellipse" | "star" | "polygon" | "path";
      points?: number;
      outer_radius?: number;
      inner_radius?: number;
      vertices?: number[][];
      in_tangents?: number[][];
      out_tangents?: number[][];
      closed?: boolean;
      size?: number[];
      fill?: number[];
      stroke?: number[];
      stroke_width?: number;
      roundness?: number;
      fill_opacity?: number;
      stroke_opacity?: number;
      dashes?: number[];
      line_cap?: "butt" | "round" | "square";
      line_join?: "miter" | "round" | "bevel";
      name?: string;
      position?: number[];
      rotation?: number;
      opacity?: number;
    };
    at?: "top" | "bottom";
  };
  add_shape_modifier: {
    layer_id: number;
    modifier: "trim_paths" | "repeater" | "round_corners";
    group_index?: number;
    params?: { [key: string]: number | string | boolean | number[] };
  };
  align_layers: {
    layer_ids: number[];
    align?: "left" | "h_center" | "right" | "top" | "v_center" | "bottom" | "center";
    to?: "comp" | "selection" | "layer";
    to_layer_id?: number;
    distribute?: "horizontal" | "vertical";
    margin?: number;
    time?: number;
  };
  align_to_markers: {
    layer_ids: number[];
    marker_layer_id?: number;
    from_index?: number;
    trim_to_next?: boolean;
  };
  animate: {
    layer_ids: number[];
    move: "fade" | "pop" | "grow" | "slide" | "drop" | "spin";
    phase?: "in" | "out";
    time?: number;
    duration?: number;
    style?: "snappy" | "smooth" | "spring" | "bounce" | "linear";
    direction?: "up" | "down" | "left" | "right";
    distance?: number;
    stagger?: number;
    order?: "forward" | "reverse";
  };
  apply_effect: {
    layer_id: number;
    match_name: string;
    name?: string;
    params?: { [key: string]: number | string | boolean | number[] };
  };
  apply_preset: {
    layer_id: number;
    ffx_path: string;
  };
  audio_react: {
    audio_layer_id: number;
    layer_ids: number[];
    path: string | (string | number)[];
    from: number | string | boolean | number[];
    to: number | string | boolean | number[];
    channel?: "both" | "left" | "right";
    smoothing?: number;
  };
  beat_markers: {
    audio_layer_id: number;
    bpm?: number;
    offset?: number;
    every?: number;
    sensitivity?: number;
    min_gap?: number;
    start?: number;
    end?: number;
    on?: "comp" | "layer";
    replace?: boolean;
    keep_amplitude?: boolean;
  };
  camera_move: {
    layer_id: number;
    type: "dolly" | "truck" | "pedestal" | "crane" | "pan" | "tilt" | "roll" | "orbit" | "zoom" | "rack_focus" | "path";
    start?: number;
    duration?: number;
    easing?: "linear" | "ease_in" | "ease_out" | "ease_in_out";
    combine?: boolean;
    spatial?: "smooth" | "linear";
    distance?: number;
    factor?: number;
    degrees?: number;
    vertical_degrees?: number;
    target?: number[];
    step_degrees?: number;
    to_zoom?: number;
    to_focal_length?: number;
    to_fov?: number;
    to_focus_distance?: number;
    to_layer_id?: number;
    enable_dof?: boolean;
    waypoints?: {
      t: number;
      position?: number[];
      point_of_interest?: number[];
    }[];
  };
  camera_rig: {
    layer_id: number;
    action: "create" | "remove";
    delete_controls?: boolean;
  };
  camera_shake: {
    layer_id: number;
    target?: "position" | "point_of_interest" | "rotation" | "all";
    amount?: number;
    rotation_amount?: number;
    frequency?: number;
    octaves?: number;
    include_depth?: boolean;
    seed?: number;
    remove?: boolean;
  };
  copy_animation: {
    from_layer_id: number;
    path: string | (string | number)[];
    to_layer_ids: number[];
    to_path?: string | (string | number)[];
    offset_seconds?: number;
    stagger_seconds?: number;
  };
  create_comp: {
    name: string;
    width: number;
    height: number;
    fps: number;
    duration: number;
    bg_color?: number[];
  };
  delete_item: {
    item_id: number;
    force?: boolean;
  };
  delete_layer: {
    layer_id: number;
  };
  delete_marker: {
    layer_id?: number;
    comp_id?: number;
    index?: number;
    time?: number;
  };
  delete_range: {
    comp_id: number;
    start: number;
    end: number;
    ripple?: boolean;
    layer_ids?: number[];
    shorten_comp?: boolean;
    move_markers?: boolean;
  };
  duck_music: {
    music_layer_id: number;
    under_layer_ids?: number[];
    amount?: number;
    attack?: number;
    release?: number;
    mode?: "auto" | "span" | "loudness";
    min_level?: number;
  };
  duplicate_layer: {
    layer_id: number;
    count?: number;
    name?: string;
    offset_seconds?: number;
  };
  edit_effect: {
    layer_id: number;
    effect_index: number;
    action: "remove" | "enable" | "disable";
  };
  edit_keyframes: {
    layer_id: number;
    path: string | (string | number)[];
    edits: ({
      action: "set" | "move" | "delete";
      t?: number;
      index?: number;
      to?: number;
      v?: number | string | boolean | number[] | { [key: string]: unknown };
      interp?: "linear" | "bezier" | "hold" | "spring" | "bounce";
      ease_in?: "easy" | {
        speed?: number;
        influence?: number;
      };
      ease_out?: "easy" | {
        speed?: number;
        influence?: number;
      };
      spatial_in?: number[];
      spatial_out?: number[];
      auto_bezier?: boolean;
      continuous?: boolean;
      roving?: boolean;
    })[];
  };
  find_effects: {
    query: string;
  };
  find_fonts: {
    query?: string;
    limit?: number;
  };
  find_sound_cues: {
    comp_id: number;
    layer_ids?: number[];
    start?: number;
    end?: number;
    max?: number;
    density?: "sparse" | "normal" | "dense";
    min_gap?: number;
  };
  get_camera: {
    layer_id: number;
    time?: number;
  };
  get_comp: {
    comp_id: number;
    name?: string;
    kind?: "text" | "shape" | "solid" | "footage" | "precomp" | "null" | "adjustment" | "camera" | "light";
    at?: number;
    limit?: number;
    offset?: number;
  };
  get_keyframes: {
    layer_id: number;
    path: string | (string | number)[];
  };
  get_layer: {
    layer_id?: number;
    layer_ids?: number[];
    time?: number;
  };
  get_project: { [key: string]: unknown };
  get_text: {
    layer_id: number;
    time?: number;
  };
  import_footage: {
    path: string;
    as?: "footage" | "sequence";
  };
  insert_time: {
    comp_id: number;
    at: number;
    duration: number;
    layer_ids?: number[];
    extend_comp?: boolean;
    move_markers?: boolean;
    snap?: boolean;
  };
  link_layers: {
    layer_ids: number[];
    parent_id?: number | null;
    new_null?: {
      name?: string;
      position?: number[];
      three_d?: boolean;
    };
    jump?: boolean;
  };
  list_markers: {
    layer_id?: number;
    comp_id?: number;
  };
  list_properties: {
    layer_id: number;
    group_path?: string | (string | number)[];
    depth?: number;
    time?: number;
    all?: boolean;
  };
  open_project: {
    path?: string;
    new?: boolean;
    discard_unsaved?: boolean;
  };
  precompose: {
    layer_ids: number[];
    name: string;
    move_attributes?: boolean;
  };
  preview_frame: {
    comp_id: number;
    time: number | number[];
    size?: number;
  };
  reorder_layer: {
    layer_id: number;
    to?: "top" | "bottom" | "up" | "down";
    index?: number;
    before_layer_id?: number;
    after_layer_id?: number;
  };
  replace_source: {
    layer_id: number;
    item_id: number;
    fix_expressions?: boolean;
  };
  review_motion: {
    comp_id: number;
    max_hold?: number;
    min_text?: number;
    max?: number;
    all?: boolean;
    scene?: boolean;
  };
  run_jsx: {
    code: string;
  };
  save_project: {
    path?: string;
    overwrite?: boolean;
  };
  sequence_layers: {
    layer_ids: number[];
    overlap?: number;
    start?: number;
  };
  set_3d: {
    layer_id: number;
    three_d?: boolean;
    position?: number[];
    z?: number;
    anchor?: number[];
    scale?: number[];
    orientation?: number[];
    rotation?: {
      x?: number;
      y?: number;
      z?: number;
    };
    material?: {
      casts_shadows?: "off" | "on" | "only";
      accepts_shadows?: boolean;
      accepts_lights?: boolean;
      light_transmission?: number;
      ambient?: number;
      diffuse?: number;
      specular_intensity?: number;
      specular_shininess?: number;
      metal?: number;
      reflection_intensity?: number;
      reflection_sharpness?: number;
      reflection_rolloff?: number;
      transparency?: number;
      transparency_rolloff?: number;
      index_of_refraction?: number;
    };
    time?: number;
  };
  set_3d_view: {
    view: "active_camera" | "default" | "front" | "left" | "top" | "back" | "right" | "bottom" | "custom_1" | "custom_2" | "custom_3";
    comp_id?: number;
  };
  set_anchor: {
    layer_id: number;
    anchor?: "center" | "top_left" | "top" | "top_right" | "left" | "right" | "bottom_left" | "bottom" | "bottom_right";
    point?: number[];
    keep_position?: boolean;
    time?: number;
  };
  set_camera: {
    layer_id: number;
    name?: string;
    two_node?: boolean;
    zoom?: number;
    focal_length?: number;
    fov?: number;
    depth_of_field?: boolean;
    focus_distance?: number;
    focus_on_layer_id?: number;
    aperture?: number;
    blur_level?: number;
    iris_shape?: number;
    iris_rotation?: number;
    iris_roundness?: number;
    iris_aspect_ratio?: number;
    iris_diffraction_fringe?: number;
    highlight_gain?: number;
    highlight_threshold?: number;
    highlight_saturation?: number;
    position?: number[];
    point_of_interest?: number[];
    orientation?: number[];
    rotation?: {
      x?: number;
      y?: number;
      z?: number;
    };
    look_at_layer_id?: number;
    follow?: boolean;
    time?: number;
  };
  set_comp: {
    comp_id: number;
    name?: string;
    width?: number;
    height?: number;
    fps?: number;
    duration?: number;
    bg_color?: number[];
    pixel_aspect?: number;
    work_area?: {
      start?: number;
      duration?: number;
    };
    motion_blur?: boolean;
    shutter_angle?: number;
    shutter_phase?: number;
    frame_blending?: boolean;
  };
  set_expression: {
    layer_id?: number;
    layer_ids?: number[];
    path: string | (string | number)[];
    expression: string;
  };
  set_keyframes: {
    layer_id: number;
    path: string | (string | number)[];
    keys: ({
      t: number;
      v: number | string | boolean | number[] | { [key: string]: unknown };
      interp?: "linear" | "bezier" | "hold" | "spring" | "bounce";
      ease_in?: "easy" | {
        speed?: number;
        influence?: number;
      };
      ease_out?: "easy" | {
        speed?: number;
        influence?: number;
      };
    })[];
    merge?: boolean;
  };
  set_layer: {
    layer_id: number;
    name?: string;
    start?: number;
    in?: number;
    out?: number;
    parent_id?: number | null;
    blend_mode?: string;
    enabled?: boolean;
    stretch?: number;
    three_d?: boolean;
    shy?: boolean;
    solo?: boolean;
    locked?: boolean;
    label?: number;
    motion_blur?: boolean;
    time_remap?: boolean;
    separate_dimensions?: boolean;
    auto_orient?: "path" | "off";
    frame_blending?: "off" | "frame_mix" | "pixel_motion";
    quality?: "best" | "draft" | "wireframe";
    sampling?: "bilinear" | "bicubic";
    collapse?: boolean;
    guide?: boolean;
    adjustment?: boolean;
    effects?: boolean;
    audio?: boolean;
    preserve_transparency?: boolean;
    solid_color?: number[];
    solid_size?: number[];
  };
  set_light: {
    layer_id: number;
    name?: string;
    light_type?: "point" | "spot" | "parallel" | "ambient";
    intensity?: number;
    color?: number[];
    cone_angle?: number;
    cone_feather?: number;
    falloff?: "none" | "smooth" | "inverse_square_clamped";
    falloff_radius?: number;
    falloff_distance?: number;
    casts_shadows?: boolean;
    shadow_darkness?: number;
    shadow_diffusion?: number;
    position?: number[];
    point_of_interest?: number[];
    orientation?: number[];
    rotation?: {
      x?: number;
      y?: number;
      z?: number;
    };
    time?: number;
  };
  set_playhead: {
    comp_id: number;
    time: number;
    snap?: boolean;
  };
  set_property: {
    layer_id: number;
    path: string | (string | number)[];
    value: number | string | boolean | number[] | { [key: string]: unknown };
    time?: number;
  };
  set_text: {
    layer_id: number;
    time?: number;
    text?: string;
    font?: string;
    size?: number;
    color?: number[];
    tracking?: number;
    leading?: number;
    auto_leading?: boolean;
    baseline_shift?: number;
    horizontal_scale?: number;
    vertical_scale?: number;
    faux_bold?: boolean;
    faux_italic?: boolean;
    all_caps?: boolean;
    small_caps?: boolean;
    superscript?: boolean;
    subscript?: boolean;
    ligatures?: boolean;
    tsume?: number;
    stroke_color?: number[];
    stroke_width?: number;
    stroke?: boolean;
    stroke_over_fill?: boolean;
    fill?: boolean;
    justification?: "left" | "center" | "right" | "justify" | "justify_center" | "justify_right" | "justify_all";
    first_line_indent?: number;
    left_indent?: number;
    right_indent?: number;
    space_before?: number;
    space_after?: number;
    box_size?: number[];
  };
  set_track_matte: {
    layer_id: number;
    matte_layer_id: number | null;
    type?: "alpha" | "alpha_inverted" | "luma" | "luma_inverted";
  };
  shift_layers: {
    layer_ids: number[];
    offset_seconds: number;
  };
  split_layer: {
    layer_ids: number[];
    time: number;
    snap?: boolean;
  };
  stagger: {
    layer_ids: number[];
    path: string | (string | number)[];
    offset_seconds: number;
    order?: "forward" | "reverse";
  };
  text_reveal: {
    layer_id: number;
    style?: "rise" | "drop" | "fade" | "pop" | "blur" | "typewriter";
    by?: "chars" | "words" | "lines";
    phase?: "in" | "out";
    time?: number;
    duration?: number;
    stagger?: number;
    ease?: "snappy" | "smooth" | "spring" | "bounce" | "linear";
    order?: "forward" | "reverse" | "center" | "random";
    distance?: number;
    mask?: boolean;
  };
  text_to_shapes: {
    layer_id: number;
  };
  transition: {
    comp_id: number;
    time: number;
    type?: "wipe" | "bars" | "iris";
    duration?: number;
    color?: number[];
    direction?: "up" | "down" | "left" | "right";
    bars?: number;
    center?: number[];
  };
  trim_comp: {
    comp_id: number;
    to: "work_area" | "layers";
  };
  update_marker: {
    layer_id?: number;
    comp_id?: number;
    index?: number;
    time?: number;
    to_time?: number;
    comment?: string;
    duration?: number;
    chapter?: string;
    url?: string;
    label?: number;
  };
}
