#!/usr/bin/env node
// Builds panel/host/host.jsx, the single ExtendScript file the CEP panel loads, from the sources in host/.
//
// The sources are fragments of one closure: everything except json.jsx is wrapped in
//   var AEM = (function () { var C = {}; ... return { dispatch: dispatch }; })();
// so helpers and commands share scope without globals. Order only matters for json.jsx (first) and the
// wrapper; function declarations are hoisted and constants are only read when a command runs.
//
// Usage: node scripts/build-host.mjs        (also run by `npm run build`)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const HOST_DIR = path.join(ROOT, "host");
export const HOST_OUT = path.join(ROOT, "panel", "host", "host.jsx");

/** Emitted before the AEM closure. */
export const PRELUDE = ["json.jsx"];
/** Emitted inside the AEM closure, in this order. Add new files here. */
export const MODULES = [
  "core/util.jsx",
  "core/lookup.jsx",
  "core/describe.jsx",
  "core/keys.jsx",
  "core/shapes.jsx",
  "core/timing.jsx",
  "core/vector.jsx",
  "core/scene3d.jsx",
  "core/layout.jsx",
  "commands/inspect.jsx",
  "commands/project.jsx",
  "commands/layers.jsx",
  "commands/timeline.jsx",
  "commands/masks.jsx",
  "commands/animate.jsx",
  "commands/text.jsx",
  "commands/scene3d.jsx",
  "commands/design.jsx",
  "commands/output.jsx",
  "dispatch.jsx",
];
export const HOST_SOURCES = [...PRELUDE, ...MODULES];

const read = (rel) => fs.readFileSync(path.join(HOST_DIR, rel), "utf8").replace(/\r\n/g, "\n").replace(/\n+$/, "");
const banner = (rel) => `// ---- host/${rel} ----`;

/** Top-level names in the shared closure must be unique, or one file silently overrides another. */
function checkDuplicates() {
  const seen = new Map();
  const problems = [];
  for (const rel of MODULES) {
    read(rel).split("\n").forEach((line, i) => {
      const m = /^(?:function\s+(\w+)\s*\(|var\s+(\w+)\s*=|C\.(\w+)\s*=\s*function)/.exec(line);
      if (!m) return;
      const name = m[1] ? m[1] : m[2] ? m[2] : "C." + m[3];
      const where = `host/${rel}:${i + 1}`;
      if (seen.has(name)) problems.push(`${name} is defined in ${seen.get(name)} and ${where}`);
      else seen.set(name, where);
    });
  }
  if (problems.length) throw new Error("Duplicate top-level names in host/:\n  " + problems.join("\n  "));
}

/** Returns the contents of panel/host/host.jsx. */
export function buildHost() {
  checkDuplicates();
  const indent = (s) => s.split("\n").map((l) => (l ? "  " + l : l)).join("\n");
  const parts = [
    "// AE Motion MCP host script (ExtendScript, ES3), loaded by the CEP panel.",
    "// GENERATED by scripts/build-host.mjs from host/ -- do not edit; edit the files in host/ and run `npm run build`.",
    "",
    ...PRELUDE.flatMap((rel) => [banner(rel), read(rel), ""]),
    "var AEM = (function () {",
    "  var C = {}; // command name -> function(args); one per bridged tool",
    "",
    ...MODULES.flatMap((rel) => [indent(banner(rel)), indent(read(rel)), ""]),
    "  return { dispatch: dispatch };",
    "})();",
    "",
  ];
  return parts.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    fs.mkdirSync(path.dirname(HOST_OUT), { recursive: true });
    fs.writeFileSync(HOST_OUT, buildHost());
    console.log(`built ${path.relative(ROOT, HOST_OUT)} from ${HOST_SOURCES.length} files in host/`);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
