// Writes host/args.d.ts: the argument types of every bridged tool, generated from the server's own input schemas
// (tools/list of the built dist/index.js), so the host commands are type-checked against exactly what the server
// sends: C.add_layer = function (a: Args["add_layer"]) { ... }. test/static-checks.ts fails when the file is stale.
//
//   npm run build:server && node scripts/host-args.ts        (npm run build does this)
import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const ARGS_OUT = path.join(ROOT, "host", "args.d.ts");

type Schema = {
  type?: string | string[]; properties?: Record<string, Schema>; required?: string[]; additionalProperties?: boolean | Schema;
  items?: Schema; prefixItems?: Schema[]; enum?: unknown[]; const?: unknown; anyOf?: Schema[]; oneOf?: Schema[];
};

/** A TypeScript type for a JSON schema (the subset zod produces for these tools). */
export function tsType(s: Schema, indent = ""): string {
  if (s.anyOf ?? s.oneOf) return [...new Set((s.anyOf ?? s.oneOf)!.map((x) => tsType(x, indent)))].join(" | ");
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  const t = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  if (t.length > 1) return t.map((x) => tsType({ ...s, type: x }, indent)).join(" | ");
  switch (t[0]) {
    case "string": return "string";
    case "number": case "integer": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "array":
      if (s.prefixItems) return "[" + s.prefixItems.map((x) => tsType(x, indent)).join(", ") + "]";
      return s.items ? wrap(tsType(s.items, indent)) + "[]" : "unknown[]";
    case "object": {
      const props = Object.entries(s.properties ?? {});
      const extra = typeof s.additionalProperties === "object" ? tsType(s.additionalProperties, indent) : null;
      if (!props.length) return `{ [key: string]: ${extra ?? "unknown"} }`;
      const req = new Set(s.required ?? []), inner = indent + "  ";
      const lines = props.map(([k, v]) => `${inner}${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}${req.has(k) ? "" : "?"}: ${tsType(v, inner)};`);
      if (extra) lines.push(`${inner}[key: string]: ${extra};`);
      return "{\n" + lines.join("\n") + "\n" + indent + "}";
    }
    default: return "unknown";
  }
}
const wrap = (t: string): string => (/^[\w"[\]{}]+$|^\{[\s\S]*\}$/.test(t) && !t.includes(" | ") ? t : `(${t})`);

/** The file's text for a tools/list result (bridged tools only: SERVER_ONLY have no host command). */
export function argsFile(tools: { name: string; inputSchema: Schema }[], serverOnly: Set<string>): string {
  const body = tools.filter((t) => !serverOnly.has(t.name)).sort((a, b) => a.name.localeCompare(b.name))
    .map((t) => `  ${t.name}: ${tsType(t.inputSchema, "  ")};`).join("\n");
  return `// Generated by scripts/host-args.ts from the server's tool schemas (npm run build). Do not edit.
// The arguments each host command receives: C.<tool> = function (a: Args["<tool>"]) { ... }.

interface Args {
${body}
}
`;
}

/** Tools implemented in the server only (no C.<name>); keep in sync with test/static-checks.ts. */
export const SERVER_ONLY = new Set(["render_start", "render_status", "render_cancel", "check_for_updates", "batch", "load_tools"]);

export async function listTools(): Promise<{ name: string; inputSchema: Schema }[]> {
  const server = path.join(ROOT, "dist", "index.js");
  if (!fs.existsSync(server)) throw new Error("dist/index.js missing: run `npm run build:server` first");
  const p = spawn(process.execPath, [server], { env: { ...process.env, AE_MCP_UPDATE_CHECK: "0", AE_MCP_TOOLSETS: "" }, stdio: ["pipe", "pipe", "ignore"] });
  let buf = "";
  const tools = await new Promise<{ name: string; inputSchema: Schema }[]>((resolve, reject) => {
    p.on("error", reject);
    p.stdout.on("data", (d) => {
      buf += d;
      for (const line of buf.split("\n")) { try { const m = JSON.parse(line); if (m.id === 2) resolve(m.result.tools); } catch { /* partial line */ } }
    });
    const send = (o: object): boolean => p.stdin.write(JSON.stringify(o) + "\n");
    send({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "host-args", version: "1" } } });
    send({ jsonrpc: "2.0", method: "notifications/initialized" });
    send({ jsonrpc: "2.0", id: 2, method: "tools/list" });
  });
  p.kill();
  return tools;
}

if (process.argv[1] && import.meta.url === new URL("file://" + path.resolve(process.argv[1])).href) {
  fs.writeFileSync(ARGS_OUT, argsFile(await listTools(), SERVER_ONLY));
  console.log("wrote " + path.relative(ROOT, ARGS_OUT));
}
